import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import "reflect-metadata";
import styles from "../styles/Home.module.css";
import NavBar from "./components/NavBar";
import ListCard from "./components/CardList";
import Container from "@mui/material/Container";
import UnitOfWork from "../interfaces/database/unit-of-work";
import { Product } from "../interfaces/entity/product";

function Home({ products }: { products: Array<Product> }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mua bán account games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="lg">
        <NavBar></NavBar>
      </Container>

      <Container maxWidth="lg" style={{ marginTop: 10 }}>
        <ListCard products={products}></ListCard>
      </Container>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const uow = new UnitOfWork();
  await uow.initialize();

  const products = await uow.ProuductRepository.find({
    relations: {
      productItems: true,
    },
  });

  return {
    props: { products: products.map((p) => p.toJSON()) },
  };
}
export default Home;
